/**
 * Class for MainMenu
 * The first window a user sees, contains buttons to access other parts of the program
 * @author Casey Harford
 */

package QuotationsPackage;

import java.awt.EventQueue;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;

public class MainMenu extends javax.swing.JFrame {
	
    /** Creates new form MainMenu */
    public MainMenu() {
        initComponents();
    }

    /** This method is called from within the constructor to			// This method was generated by NetBeans
     * initialize the form.												// I modified as necessary.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        showQuotesButton = new javax.swing.JButton();
        loginButton = new javax.swing.JButton();
        showQuotesLabel = new javax.swing.JLabel();
        loginLabel = new javax.swing.JLabel();
        signupButton = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        showQuotesButton.setText("Show Quotes");
        showQuotesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showQuotesButtonActionPerformed(evt);
            }
        });

        if(Quotations.logged_in) loginButton.setText("Logout");
        else
        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        showQuotesLabel.setText("Show quotes by clicking the button below.");

        if(Quotations.logged_in) loginLabel.setText("You are logged in as "+ Quotations.currentUserFirst + " " + Quotations.currentUserLast + ".");
        else
        loginLabel.setText("You must be logged in to save changes.");

        signupButton.setText("Sign up");
        signupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupButtonActionPerformed(evt);
            }
        });

        titleLabel.setFont(new java.awt.Font("Lucida Grande", 1, 36));
        titleLabel.setText("Quotations");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(titleLabel))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(loginButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(showQuotesButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(signupButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 73, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(75, 75, 75)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.CENTER)
                            .add(loginLabel)
                            .add(showQuotesLabel))))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(new java.awt.Component[] {loginButton, showQuotesButton, signupButton}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(titleLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(showQuotesLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(loginLabel)
                .add(22, 22, 22)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(loginButton)
                    .add(showQuotesButton)
                    .add(signupButton))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	/**
	 * showQuotes button, creates a thread for the showQuotes frame and starts it
	 * @param evt	The ActionEvent occuring (show quotes button)
	 */
	private void showQuotesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showQuotesButtonActionPerformed
	
	    /* Create and display the form */
	    EventQueue.invokeLater(new Runnable() {

	       @Override
	       /**
	        * run method, used start another window, off the current thread
	        */
	       public void run() {
	           
	           /* create the frame */
	           final JFrame frame = new JFrame();
	           
	           /* add content, show quotes */
	           frame.setContentPane(new ShowQuotes());
	           
	           /* make sure that if the user clicks the X, to not exit, just dispose */
	           frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
	           
	           /* set the dimensions */
	           frame.pack();
	           
	           /* make the frame visible */
	           frame.setVisible(true);
	           
	           /* don't allow resize */
	           frame.setResizable(false);
	           
	           /* since the window is being disposed, we must over ride the windowClosing method */
	           frame.addWindowListener(new WindowAdapter() {
	               @Override
	               /**
	                * windowClosing method, will dispose this window, and return user to main menu,
	                * by opening the main menu window before disposing.
	                * @param evt    the action occuring(closing window, user most likely pressing the X)
	                */
	               public void windowClosing(WindowEvent evt) {
	                   
	                   /* open the main menu */
	                   Quotations.openMainMenu();
	                   
	                   /* and close this one */
	                   frame.dispose();
	               }
	           });
	       }
	    });
	    
	    /* once show quotes has been started, close this window */
	    this.dispose();
	}//GEN-LAST:event_showQuotesButtonActionPerformed

	/**
	 * loginButton action, displays LoginWindow for user to login if the user is not logged in,
	 * however, the caption for the button changes to logout if the user does login, therefore 
	 * logout is also handled in this method.
	 * @param evt	the event occuring(login button pressed)
	 */
	private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
	
        /* check if user is logged in, if they are we will be loggin them out */
	    if(Quotations.logged_in) {
	        
	        /* set initial value to false, meaning user is not logged in */
	        Quotations.logged_in = false;
	        
	        /* set initial value for currentUser, 0(unknown)*/
	        Quotations.currentUserID = 0;
	        
	        /* set initial value of currentUserFirst(null)*/
	        Quotations.currentUserFirst = null;

	        /* set initial value of currentUserLast(null)*/
	        Quotations.currentUserLast = null;
	        
	        /* open the main menu */
	        Quotations.openMainMenu();
	        
	        /* and close this one */
	        this.dispose();
	        
	        /* should not continue with code below, since the user is now logged out */
	        return;
	    }
	    
	    /* Create and display the form */
	    java.awt.EventQueue.invokeLater(new Runnable() {

	        @Override
	        /**
	         * run method, used here to start the login window
	         */
	        public void run() {
	            
	            /* instantiate a new login window */
	            final LoginWindow login = new LoginWindow();
	            
	            /* make it visible */
	            login.setVisible(true);
	            
	            /* should not be resizable */
	            login.setResizable(false);
	            
	            /* defining the close operation here */
	            login.addWindowListener(new WindowAdapter() {
	                @Override
	                /**
	                 * method windowClosing, over ridden to provide more functionality.
	                 * main menu will be opened up, then this window will be disposed of.
	                 */
	                public void windowClosing(WindowEvent evt) {
	                    
	                    /* open the main menu */
	                    Quotations.openMainMenu();
	                    
	                    /* and close this one */
	                    login.dispose();
	                }
	            });
	        }
	    });
	    
	    /* finished opening the login window, close this one */
	    this.dispose();
	}//GEN-LAST:event_loginButtonActionPerformed

	/**
	 * signupButton action, displays signup window for user to create new account
	 * @param evt	the event occuring(user pressed signup)
	 */
	private void signupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupButtonActionPerformed
	    
	    /* Create and display the form */
	    java.awt.EventQueue.invokeLater(new Runnable() {

	        @Override
	        /**
	         * run method, used to start the new user window
	         */
	        public void run() {
	            
	            /* instantiating a new window */
	            final NewUser newUserWindow = new NewUser();
	            
	            /* make it visible */
	            newUserWindow.setVisible(true);
	            
	            /* but not resizable */
	            newUserWindow.setResizable(false);
	            
	            /* customized the close operation */
	            newUserWindow.addWindowListener(new WindowAdapter() {
	                @Override
	                /**
	                 * windowClosing method, used to open the main window, and close the new user window
	                 * @param evt   action being performed(closing window)
	                 */
	                public void windowClosing(WindowEvent evt) {
	                    
	                    /* open the main window */
	                    Quotations.openMainMenu();
	                    
	                    /* and close this one */
	                    newUserWindow.dispose();
	                }
	            });
	        }
	    });
	    
	    /* finished opening new user window, close this one */
	    this.dispose();
	}//GEN-LAST:event_signupButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JButton showQuotesButton;
    private javax.swing.JLabel showQuotesLabel;
    private javax.swing.JButton signupButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
