/*
 * Class for ShowQuotes
 * Displays a JTable full of quotes, along with the ability to add quotes, 
 * modify/delete(if database permissions allow), and like quotes.
 * @author Casey Harford
 */

package QuotationsPackage;

import java.beans.Beans;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.RollbackException;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;

public class ShowQuotes extends JPanel {
    
    public ShowQuotes() {
        initComponents();
        if (!Beans.isDesignTime()) {
            entityManager.getTransaction().begin();
        }
        searchField.setText("");
    }

    /** This method is called from within the constructor to		// This method was generated with NetBeans,
     * initialize the form.											// I modified as necessary.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("quotationsPU").createEntityManager();
        query = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT q FROM Quotes q");
        list = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(query.getResultList());
        searchByGroup = new javax.swing.ButtonGroup();
        rowSorterToStringConverter1 = new QuotationsPackage.RowSorterToStringConverter();
        masterScrollPane = new javax.swing.JScrollPane();
        masterTable = new javax.swing.JTable();
        quoteLabel = new javax.swing.JLabel();
        authorIDLabel = new javax.swing.JLabel();
        userIDLabel = new javax.swing.JLabel();
        likesLabel = new javax.swing.JLabel();
        quoteField = new javax.swing.JTextField();
        authorIDField = new javax.swing.JTextField();
        userIDField = new javax.swing.JTextField();
        likesField = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();
        newButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        quoteRadioButton = new javax.swing.JRadioButton();
        userRadioButton = new javax.swing.JRadioButton();
        authorRadioButton = new javax.swing.JRadioButton();
        searchField = new javax.swing.JTextField();
        likeButton = new javax.swing.JButton();
        quoteIDField = new javax.swing.JTextField();
        quoteIDLabel = new javax.swing.JLabel();
        searchByLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        quoteLabel1 = new javax.swing.JLabel();
        authorCombo = new javax.swing.JComboBox();

        FormListener formListener = new FormListener();

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ObjectProperty.create(), rowSorterToStringConverter1, org.jdesktop.beansbinding.BeanProperty.create("table"));
        bindingGroup.addBinding(binding);

        masterTable.setAutoCreateRowSorter(true);
        masterTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        masterTable.setGridColor(new java.awt.Color(204, 204, 204));
        masterTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        masterTable.setShowGrid(true);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, list, masterTable);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${quote}"));
        columnBinding.setColumnName("Quote");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${author}"));
        columnBinding.setColumnName("Author");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${user}"));
        columnBinding.setColumnName("User");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${likes}"));
        columnBinding.setColumnName("Likes");
        columnBinding.setColumnClass(Integer.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        masterScrollPane.setViewportView(masterTable);

        quoteLabel.setText("Quote:");

        authorIDLabel.setText("Author ID:");

        userIDLabel.setText("User ID:");

        likesLabel.setText("Likes:");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.quote}"), quoteField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue(null);
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), quoteField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        authorIDField.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.authorID}"), authorIDField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue(null);
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), authorIDField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        userIDField.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.userID}"), userIDField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue(null);
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), userIDField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        likesField.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.likes}"), likesField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue(null);
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), likesField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        saveButton.setText("Save");
        saveButton.addActionListener(formListener);

        refreshButton.setText("Refresh");
        refreshButton.addActionListener(formListener);

        newButton.setText("New");
        newButton.addActionListener(formListener);

        deleteButton.setText("Delete");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), deleteButton, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        deleteButton.addActionListener(formListener);

        searchByGroup.add(quoteRadioButton);
        quoteRadioButton.setText("Quote");

        searchByGroup.add(userRadioButton);
        userRadioButton.setText("User");

        searchByGroup.add(authorRadioButton);
        authorRadioButton.setSelected(true);
        authorRadioButton.setText("Author");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${rowSorter}"), searchField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setConverter(rowSorterToStringConverter1);
        bindingGroup.addBinding(binding);

        searchField.addActionListener(formListener);

        likeButton.setText("Like");
        likeButton.addActionListener(formListener);

        quoteIDField.setEditable(false);
        quoteIDField.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.quoteNumber}"), quoteIDField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        quoteIDLabel.setText("Quote ID:");

        searchByLabel.setText("Search by:");

        titleLabel.setFont(new java.awt.Font("Lucida Grande", 1, 36));
        titleLabel.setText("Quotations");

        quoteLabel1.setText("Author:");

        /*
        authorCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.authorID}"), authorCombo, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        */

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, masterScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(searchField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(newButton)
                                    .add(searchByLabel))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(layout.createSequentialGroup()
                                        .add(authorRadioButton)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                        .add(userRadioButton)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                        .add(quoteRadioButton))
                                    .add(layout.createSequentialGroup()
                                        .add(deleteButton)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(refreshButton)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(saveButton)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(likeButton)))))
                        .add(20, 20, 20)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(quoteIDLabel)
                            .add(userIDLabel)
                            .add(authorIDLabel))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, authorIDField)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, quoteIDField)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, userIDField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(quoteLabel)
                            .add(quoteLabel1))
                        .add(33, 33, 33)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(quoteField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
                            .add(layout.createSequentialGroup()
                                .add(authorCombo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 182, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(274, 274, 274)
                                .add(likesLabel)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(likesField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))))
                    .add(titleLabel))
                .addContainerGap())
        );

        layout.linkSize(new java.awt.Component[] {deleteButton, newButton, refreshButton, saveButton}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(titleLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(masterScrollPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 132, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(quoteLabel)
                    .add(quoteField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(likesField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(quoteLabel1)
                        .add(likesLabel))
                    .add(authorCombo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(saveButton)
                    .add(refreshButton)
                    .add(deleteButton)
                    .add(newButton)
                    .add(likeButton)
                    .add(quoteIDField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(quoteIDLabel))
                .add(7, 7, 7)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(quoteRadioButton)
                    .add(userRadioButton)
                    .add(authorRadioButton)
                    .add(searchByLabel)
                    .add(userIDField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(userIDLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(searchField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(authorIDField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(authorIDLabel))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bindingGroup.bind();
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == saveButton) {
                ShowQuotes.this.saveButtonActionPerformed(evt);
            }
            else if (evt.getSource() == refreshButton) {
                ShowQuotes.this.refreshButtonActionPerformed(evt);
            }
            else if (evt.getSource() == newButton) {
                ShowQuotes.this.newButtonActionPerformed(evt);
            }
            else if (evt.getSource() == deleteButton) {
                ShowQuotes.this.deleteButtonActionPerformed(evt);
            }
            else if (evt.getSource() == likeButton) {
                ShowQuotes.this.likeButtonActionPerformed(evt);
            }
            else if (evt.getSource() == searchField) {
                ShowQuotes.this.searchFieldActionPerformed(evt);
            }
        }
    }// </editor-fold>//GEN-END:initComponents

    /**
	 * refreshButton action, refreshes the table with current data from the database
	 * @param evt	ActionEvent that occurs(clicking refresh)
	 */
    @SuppressWarnings("unchecked")
    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        entityManager.getTransaction().rollback();
        entityManager.getTransaction().begin();
        java.util.Collection data = query.getResultList();
        for (Object entity : data) {
            entityManager.refresh(entity);
        }
        list.clear();
        list.addAll(data);
    }//GEN-LAST:event_refreshButtonActionPerformed
    
	/**
	 * deleteButton action, deletes the currently selected quote, requires user to be logged in
	 * @param evt	ActionEvent that occurs(clicking delete)
	 */
    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        if(!Quotations.logged_in) {
            JOptionPane.showMessageDialog(this,"You must be logged in to delete quotes.");
            return;
        }
        int[] selected = masterTable.getSelectedRows();
        List<QuotationsPackage.Quotes> toRemove = new ArrayList<QuotationsPackage.Quotes>(selected.length);
        for (int idx = 0; idx < selected.length; idx++) {
            QuotationsPackage.Quotes q = list.get(masterTable.convertRowIndexToModel(selected[idx]));
            toRemove.add(q);
            entityManager.remove(q);
        }
        list.removeAll(toRemove);
        refreshButtonActionPerformed(evt);
    }//GEN-LAST:event_deleteButtonActionPerformed
    
	/**
	 * newButton action, creates a new quote, using the current user's id, requires user 
	 * to be logged in
	 * @param evt	ActionEvent ActionEvent that occurs(clicking new button)
	 */
    private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
        if(!Quotations.logged_in) {
            JOptionPane.showMessageDialog(this,"You must be logged in to add new quotes.");
            return;
        }
        
        /** get the list of authors from database */
        PreparedStatement ps;
        ResultSet rs;
        ArrayList<String> authors = new ArrayList();
        authors.add("Select Author");
        try {
            ps = (PreparedStatement) Quotations.conn.prepareStatement
                ("SELECT CONCAT(FirstName,' ',LastName) as authorName FROM Authors ORDER BY AuthorID");
            rs = ps.executeQuery();
            while(rs.next()) {
                authors.add(rs.getString("authorName"));
            }
        } 
        catch (SQLException ex) {
            Logger.getLogger(ShowQuotes.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        authorCombo.setModel(new javax.swing.DefaultComboBoxModel(authors.toArray()));
        searchField.setText("");
        QuotationsPackage.Quotes q = new QuotationsPackage.Quotes();
        entityManager.persist(q);
        list.add(q);
        int row = masterTable.getRowCount() - 1;
        masterTable.setRowSelectionInterval(row, row);
        masterTable.scrollRectToVisible(masterTable.getCellRect(row, 0, true));  
        userIDField.setText(Integer.toString(Quotations.currentUserID));
        userIDField.setEditable(false);
    }//GEN-LAST:event_newButtonActionPerformed
    
	/**
	 * saveButton action, saves the current either new post, or changes to existing(if database allows)
	 * @param evt ActionEvent that occurs(clicking save button)
	 */
    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        if(!Quotations.logged_in) {
            JOptionPane.showMessageDialog(this,"You must be logged in to save changes.");
            return;
        }
        try {
            entityManager.getTransaction().commit();
            entityManager.getTransaction().begin();
        } catch (RollbackException rex) {
            entityManager.getTransaction().begin();
            List<QuotationsPackage.Quotes> merged = new ArrayList<QuotationsPackage.Quotes>(list.size());
            for (QuotationsPackage.Quotes q : list) {
                merged.add(entityManager.merge(q));
            }
            list.clear();
            list.addAll(merged);
        }
        refreshButtonActionPerformed(evt);
    }//GEN-LAST:event_saveButtonActionPerformed

	/**
	 * searchButton action, not complete yet, may be removed in future.
	 * @param evt	event occuring(search button pressed)
	 */	
	/**
	 * likeQuote method, increments the current like by 1
	 * @param quoteID	this is the QuoteNumber to be "liked"
	 */
	private void likeQuote(int quoteID) {
	    System.out.println("Liking quote: " + quoteID);
	    ResultSet rs = null;  
	    PreparedStatement ps;
	    Connection conn = null;
	    try {
	        System.out.println("try statement, quote id: " + quoteID);
	        ps = (PreparedStatement) Quotations.conn.prepareStatement("UPDATE Quotes SET Likes=Likes+1 WHERE QuoteNumber = ?");
	        ps.setInt(1,quoteID);
	        ps.executeUpdate();
	    }
	    catch (Exception e) {}
	}
	
	/**
	 * likeButton action makes call to likeButton, then refreshes table data
	 * @param evt	ActionEvent that occurs when pressing the like button
	 */
	private void likeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_likeButtonActionPerformed
	    if(!quoteIDField.getText().equalsIgnoreCase("")) 
	        likeQuote(Integer.parseInt(quoteIDField.getText()));
	    else return;
	    entityManager.getTransaction().rollback();
	    entityManager.getTransaction().begin();
	    java.util.Collection data = query.getResultList();
	    for (Object entity : data) {
	        entityManager.refresh(entity);
	    }
	    list.clear();
	    list.addAll(data);
	}//GEN-LAST:event_likeButtonActionPerformed

private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_searchFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox authorCombo;
    private javax.swing.JTextField authorIDField;
    private javax.swing.JLabel authorIDLabel;
    private javax.swing.JRadioButton authorRadioButton;
    private javax.swing.JButton deleteButton;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JButton likeButton;
    private javax.swing.JTextField likesField;
    private javax.swing.JLabel likesLabel;
    private java.util.List<QuotationsPackage.Quotes> list;
    private javax.swing.JScrollPane masterScrollPane;
    private javax.swing.JTable masterTable;
    private javax.swing.JButton newButton;
    private javax.persistence.Query query;
    private javax.swing.JTextField quoteField;
    private javax.swing.JTextField quoteIDField;
    private javax.swing.JLabel quoteIDLabel;
    private javax.swing.JLabel quoteLabel;
    private javax.swing.JLabel quoteLabel1;
    private javax.swing.JRadioButton quoteRadioButton;
    private javax.swing.JButton refreshButton;
    private QuotationsPackage.RowSorterToStringConverter rowSorterToStringConverter1;
    private javax.swing.JButton saveButton;
    private javax.swing.ButtonGroup searchByGroup;
    private javax.swing.JLabel searchByLabel;
    private javax.swing.JTextField searchField;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField userIDField;
    private javax.swing.JLabel userIDLabel;
    private javax.swing.JRadioButton userRadioButton;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
